# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stylish < Formula
  desc ""
  homepage ""
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DaltonSW/stylish/releases/download/v1.0.2/stylish_Darwin_x86_64.tar.gz"
      sha256 "dc96d5dbb10b7b3df0bb932b4f60cbf9f5e399ea907231bf3073304e5094f246"

      def install
        bin.install "stylish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DaltonSW/stylish/releases/download/v1.0.2/stylish_Darwin_arm64.tar.gz"
      sha256 "437ccf648d32ea5af4f337b4588e91ab361f7561d54c51f2ef16442520e30bcd"

      def install
        bin.install "stylish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DaltonSW/stylish/releases/download/v1.0.2/stylish_Linux_x86_64.tar.gz"
        sha256 "adb902c81bd59773100b3facb0ecdd791987628b063d91d05701a8673a0b971e"

        def install
          bin.install "stylish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DaltonSW/stylish/releases/download/v1.0.2/stylish_Linux_arm64.tar.gz"
        sha256 "9922c55b63e0c9d430b65d3698bd4eaab4cd92d7febe4a568832a81b918226e8"

        def install
          bin.install "stylish"
        end
      end
    end
  end
end
