# This file was generated by GoReleaser. DO NOT EDIT.
cask "batterup" do
  name "batterup"
  desc ""
  homepage "https://go.dalton.dog/batterup"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "batterup"

  on_macos do
    on_intel do
      url "https://github.com/DaltonSW/BatterUp/releases/download/v#{version}/BatterUp_Darwin_x86_64.tar.gz"
      sha256 "58a27ca047b30440877884535086070198bf81add5d00efe3abea77e06aecd38"
    end
    on_arm do
      url "https://github.com/DaltonSW/BatterUp/releases/download/v#{version}/BatterUp_Darwin_arm64.tar.gz"
      sha256 "0ed701e5d02b28549c722adfb9a533777f3d3d1953e260acd37d7ea7c506be4e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DaltonSW/BatterUp/releases/download/v#{version}/BatterUp_Linux_x86_64.tar.gz"
      sha256 "e085973f1f50071fa18f52b84fb423361b8bb72dd3f5f138252a7f92dfbe691e"
    end
    on_arm do
      url "https://github.com/DaltonSW/BatterUp/releases/download/v#{version}/BatterUp_Linux_arm64.tar.gz"
      sha256 "43ebff99710b2a2629a95ce78008f6660e1e6626133c230b4ddd9624e532b45e"
    end
  end

  # No zap stanza required
end
