# This file was generated by GoReleaser. DO NOT EDIT.
cask "campfire" do
  desc ""
  homepage "https://dalton.dog/campfire"
  version "0.9.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "campfire"

  on_macos do
    on_intel do
      url "https://github.com/DaltonSW/campfire/releases/download/v0.9.2/campfire_Darwin_x86_64.tar.gz"
      sha256 "9d2157028fc0615e23f1fe1a048c278028ee2b33813130fd99b18be87dc692bc"
    end
    on_arm do
      url "https://github.com/DaltonSW/campfire/releases/download/v0.9.2/campfire_Darwin_arm64.tar.gz"
      sha256 "3961c859377f1fe6bcf95dfa7aedb21e7bde5d130a0b1665cf02fb3ab52a089d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DaltonSW/campfire/releases/download/v0.9.2/campfire_Linux_x86_64.tar.gz"
      sha256 "77d761022c4e3e1e5c9814b59f8c8a55e940c69558216149ebd79aea57d3fa40"
    end
    on_arm do
      url "https://github.com/DaltonSW/campfire/releases/download/v0.9.2/campfire_Linux_arm64.tar.gz"
      sha256 "d967c1ba310d5de9037d71951841f53bdfb084bd5f7657bf89b567b26d7111e2"
    end
  end

  # No zap stanza required
end
