# This file was generated by GoReleaser. DO NOT EDIT.
cask "prism" do
  name "prism"
  desc ""
  homepage "https://dalton.dog/prism"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prism"

  on_macos do
    on_intel do
      url "https://github.com/DaltonSW/prism/releases/download/v#{version}/prism_Darwin_x86_64.tar.gz"
      sha256 "06726966ee41ad6ce6de04e399c00f5379fa42410f289d8f18e78bb337c45921"
    end
    on_arm do
      url "https://github.com/DaltonSW/prism/releases/download/v#{version}/prism_Darwin_arm64.tar.gz"
      sha256 "125963c4d086ee1787957560f6665614b0abcb392cb9710266ce36e1c16bbad7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DaltonSW/prism/releases/download/v#{version}/prism_Linux_x86_64.tar.gz"
      sha256 "a5605ba85d6830699d6b5a679403e98fa0216426b4489a1b00258d189df60cdb"
    end
    on_arm do
      url "https://github.com/DaltonSW/prism/releases/download/v#{version}/prism_Linux_arm64.tar.gz"
      sha256 "06d2536c2a0598c1fdde85e209053264891c274ae4529539e29d0859ec64f4aa"
    end
  end

  # No zap stanza required
end
