# This file was generated by GoReleaser. DO NOT EDIT.
cask "prism" do
  name "prism"
  desc ""
  homepage "https://dalton.dog/prism"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prism"

  on_macos do
    on_intel do
      url "https://github.com/DaltonSW/prism/releases/download/v#{version}/prism_Darwin_x86_64.tar.gz"
      sha256 "98d24b3e6f9a2e1068298b28f55ad2ae3ad45ec2ca929354b3641cfd9b48f45c"
    end
    on_arm do
      url "https://github.com/DaltonSW/prism/releases/download/v#{version}/prism_Darwin_arm64.tar.gz"
      sha256 "adf6a780403fc00820fbe10fcd68937021f06c17225aadcca3fd9fb1f9a6aefb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DaltonSW/prism/releases/download/v#{version}/prism_Linux_x86_64.tar.gz"
      sha256 "f6fe4f4304475c7520cc9017911bc218e49630557b40e5208d1f68ce023b823f"
    end
    on_arm do
      url "https://github.com/DaltonSW/prism/releases/download/v#{version}/prism_Linux_arm64.tar.gz"
      sha256 "943fcc81c81238b0e4850b34149b14408668ae3af9bba6994be19c10bf453d27"
    end
  end

  # No zap stanza required
end
