# This file was generated by GoReleaser. DO NOT EDIT.
cask "prism" do
  name "prism"
  desc ""
  homepage "https://dalton.dog/prism"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prism"

  on_macos do
    on_intel do
      url "https://github.com/DaltonSW/prism/releases/download/v#{version}/prism_Darwin_x86_64.tar.gz"
      sha256 "3572c7d9d6bb9cf6507f884d612fa2fbc8a7f7b0b0e8f0c8e74a95520f3957bd"
    end
    on_arm do
      url "https://github.com/DaltonSW/prism/releases/download/v#{version}/prism_Darwin_arm64.tar.gz"
      sha256 "4a1ad8edc1654efbec1079466cc541525046b59be3cfe2f9096bd162c81f373a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DaltonSW/prism/releases/download/v#{version}/prism_Linux_x86_64.tar.gz"
      sha256 "a07263ec06abdadbfa560a1f28cba40da9eefa52c8a13a1507f9e4d47ef092e9"
    end
    on_arm do
      url "https://github.com/DaltonSW/prism/releases/download/v#{version}/prism_Linux_arm64.tar.gz"
      sha256 "4c89d91e00e09efe9e97f75684d0d40c72ab003f71df0a56e7189bd054b5fd6c"
    end
  end

  # No zap stanza required
end
