# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stylish < Formula
  desc ""
  homepage "https://dalton.dog/stylish"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DaltonSW/stylish/releases/download/v1.0.3/stylish_Darwin_x86_64.tar.gz"
      sha256 "6867bc7600a600626a4cf9d02917bf844941429c82858afd73350ce04ead54db"

      def install
        bin.install "stylish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DaltonSW/stylish/releases/download/v1.0.3/stylish_Darwin_arm64.tar.gz"
      sha256 "2e8f51271ba62d05b1ab5f25d039ad290ed94df6f964ef420c1334775e1e6a4f"

      def install
        bin.install "stylish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DaltonSW/stylish/releases/download/v1.0.3/stylish_Linux_x86_64.tar.gz"
        sha256 "3ecbfa8ab361edc82972f0dd2f23c045fc421bd0dd0958e25f208b7702f49515"

        def install
          bin.install "stylish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DaltonSW/stylish/releases/download/v1.0.3/stylish_Linux_arm64.tar.gz"
        sha256 "6d2be97afbd89b385661922913d863d45037fad0904c53369691391ade90a75d"

        def install
          bin.install "stylish"
        end
      end
    end
  end
end
