# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stylish < Formula
  desc ""
  homepage "https://dalton.dog/stylish"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DaltonSW/stylish/releases/download/v1.0.4/stylish_Darwin_x86_64.tar.gz"
      sha256 "05df8ea769a12b569efefa7b4770fa3a45b5522424bf938ec0de62c5337beb25"

      def install
        bin.install "stylish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DaltonSW/stylish/releases/download/v1.0.4/stylish_Darwin_arm64.tar.gz"
      sha256 "7cafcf5c9a71c140a7bad1938fd2d9483d2a1d7979777b25f4f84a724e2fc1e0"

      def install
        bin.install "stylish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DaltonSW/stylish/releases/download/v1.0.4/stylish_Linux_x86_64.tar.gz"
        sha256 "b8f91f94d265325bbbaa2a00018c841eae45df75327a9d8904dc340119a96b00"

        def install
          bin.install "stylish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DaltonSW/stylish/releases/download/v1.0.4/stylish_Linux_arm64.tar.gz"
        sha256 "6fb68a99417cf96b20dd3cc907c3d5739e4d80470b25d3f33c200e9fdef29022"

        def install
          bin.install "stylish"
        end
      end
    end
  end
end
